apiVersion: icm.ibm.com/v1alpha1
kind: VarnishService
metadata:
  name: varnish-service-example
spec:
  replicas: 3
  service:
    spec:
      varnishPortName: varnish-port
      selector:
        app: hello-world
      ports:
        - port: 8080
          name: varnish-port
          protocol: TCP