# Default values for all-in-one.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
varnish:
  backendsSelector:
    app: backend
  backendsPort: 80
grafana:
  admin:
    existingSecret: grafana-admin-password
  sidecar:
    datasources:
      enabled: true
      labels:
        grafana_datasource: "1"
    dashboards:
      enabled: true
      labels:
        grafana_dashboard: "1"