apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-prometheus-service-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: varnish-operator
    tier: monitoring
spec:
  selector:
    matchLabels:
      operator: varnish-operator
  endpoints:
    - port: prometheus-metrics
      interval: 15s
