matrix:
  include:
    - dist: trusty
      name: "Docs"
      sudo: false
      language: node_js
      node_js:
        - lts/*
      cache:
        directories:
          - node_modules
      before_script:
        - 'echo -e "---\nLast Commit: $TRAVIS_COMMIT\nTravis Build Number: $TRAVIS_BUILD_NUMBER" > ./docs/build-info.md'
        - npm install -g gitbook-cli
      script:
        - gitbook install
        - gitbook build ./docs docs_generated --log=debug --debug
      branches:
        only:
          - master
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: "$ghtoken"
        github_url: github.ibm.com
        on:
          branch: master
        local_dir: docs_generated
    - dist: trusty
      name: "Tests"
      sudo: false
      language: go
      go:
        - 1.13.x
      before_script:
        - go mod download
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.19.1 #install golangci-lint
        - curl -sL https://go.kubebuilder.io/dl/2.0.1/linux/amd64 | tar -xz -C /tmp/ #download kubebuilder
        - export KUBEBUILDER_ASSETS=/tmp/kubebuilder_2.0.1_linux_amd64/bin
        - export PATH=$PATH:/tmp/kubebuilder_2.0.1_linux_amd64/bin
      script:
        - golangci-lint run
        - go test ./pkg/... ./cmd/... -coverprofile=cover.out
        - "go tool cover -func=cover.out | tail -1 | awk '{print \"Total coverage: \" $3}'"
    - name: "End to End tests"
      language: go
      go:
        - 1.13.x
      services:
      - docker
      before_script:
        - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        - curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.6.0/kind-$(uname)-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
        - curl -Lo ./helm.tar.gz https://get.helm.sh/helm-v2.16.1-linux-amd64.tar.gz
        - tar -zxvf ./helm.tar.gz && sudo mv linux-amd64/helm /usr/local/bin/
        - rm -rf linux-amd64
        - go mod download
      script:
        - KUBERNETES_VERSION=1.12.10 make e2e-tests
        - KUBERNETES_VERSION=1.13.12 make e2e-tests
        - KUBERNETES_VERSION=1.14.9 make e2e-tests
        - KUBERNETES_VERSION=1.15.6 make e2e-tests
        - KUBERNETES_VERSION=1.16.3 make e2e-tests
        - KUBERNETES_VERSION=1.17.0 make e2e-tests
env:
  global:
    secure: "nRlRhTZBuKb34an2F+AXbF6FSD1Pg5Pe03P6S86r54M1R5w3nrSOqmOdcrl0aVx8q9kmDtgnIPEt1G+xeS/A6HtQ/wcHnorhIFlHOmUiLKfTNdoH/eBk/xj9pORsnDark/zuUl03y3TazW2NmvjKQQLxTnZ73ZQyyB0jp6yWdz3l7lL04ezC9MBuedWqX6jmjHeUzCpKQZgU/b0+fey+vhnodLX2ReeHAbRKAAGgVtTdYaF5fOeQrTwj8EiU+71BxKAlybTC2hZh5jX5JsS3ai6QiAjCa0OiKcPRwDpEZ6PT2oAjd8U9LA60ls20tkEl6n8FAMDRbF95IcjVV3BH3BbNemOujqpDBSDYwMYrEaV2LakKvJnXPuE1uVJnovK/2Scdt7ZgY4taREXPtvdAtGWF56WWWQ5ZEtPuRU1sk0+BWeuX2sXHZrG2b8h34yn2Q12RgjbtRuFYYO8w+VNWzg/EduEOf3IUB4nnjhtVfYHG0JMnYgN5cUortcPIhDtj3Q0cCi5T/u0WGYanoJq46ef1b2SXmOnbCI5UQVbU5oJuQOAGRescIfOiJaELE1bMkdloevW8Gg47ZQ2mrSAFJ7uwQZuPxSPYpqRU32lDwwj9NBoTycwwxDKGzWlKmlE1ajIDE6w+ziY8NQldc1nK6Fx/mRVZGSUSFeCoFSxzpfg="