name: "End to End tests"
language: go
go:
  - 1.13.x
env:
  - KUBERNETES_VERSION=1.12.10 
  - KUBERNETES_VERSION=1.13.12 
  - KUBERNETES_VERSION=1.14.9 
  - KUBERNETES_VERSION=1.15.6 
  - KUBERNETES_VERSION=1.16.3 
  - KUBERNETES_VERSION=1.17.0 
services:
- docker
before_script:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.6.0/kind-$(uname)-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
  - curl -Lo ./helm.tar.gz https://get.helm.sh/helm-v2.16.1-linux-amd64.tar.gz
  - tar -zxvf ./helm.tar.gz && sudo mv linux-amd64/helm /usr/local/bin/
  - rm -rf linux-amd64
  - go mod download
script:
  - make e2e-tests
