apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: varnishservices.icm.ibm.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.deployment.replicas
    description: desired number of varnish pods
    format: int32
    name: Desired
    type: integer
  - JSONPath: .status.deployment.readyReplicas
    description: current number of varnish pods
    format: int32
    name: Current
    type: integer
  - JSONPath: .status.deployment.updatedReplicas
    description: number of varnish pods that are up to date
    format: int32
    name: Up-To-Date
    type: integer
  - JSONPath: .status.vcl.configMapVersion
    description: version of the ConfigMap containing the VCL
    name: VCL-Version
    type: string
  - JSONPath: .status.service.cached.ip
    description: IP Address of the cached service
    name: Cached-Service-IP
    type: string
  - JSONPath: .status.service.nocached.ip
    description: IP Address of the nocached service
    name: Nocached-Service-IP
    type: string
  group: icm.ibm.com
  names:
    kind: VarnishService
    plural: varnishservices
  scope: Namespaced
  subresources:
    scale:
      specReplicasPath: .spec.deployment.replicas
      statusReplicasPath: .status.deployment.replicas
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            deployment:
              properties:
                affinity:
                  type: object
                container:
                  properties:
                    image:
                      type: string
                    imagePullPolicy:
                      type: string
                    imagePullSecret:
                      type: string
                    livenessProbe:
                      type: object
                    readinessProbe:
                      type: object
                    resources:
                      type: object
                    restartPolicy:
                      type: string
                    varnishArgs:
                      items:
                        type: string
                      type: array
                  required:
                  - image
                  type: object
                replicas:
                  format: int32
                  type: integer
                tolerations:
                  items:
                    type: object
                  type: array
              type: object
            logFormat:
              type: string
            logLevel:
              type: string
            podDisruptionBudget:
              type: object
            service:
              properties:
                prometheusAnnotations:
                  type: boolean
                varnishExporterPort:
                  type: object
                varnishPort:
                  type: object
              required:
              - varnishPort
              - varnishExporterPort
              type: object
            vclConfigMap:
              properties:
                entrypointFile:
                  type: string
                name:
                  type: string
              required:
              - name
              - entrypointFile
              type: object
          required:
          - vclConfigMap
          - deployment
          - service
          type: object
        status:
          properties:
            deployment:
              description: 'Important: Run "make" to regenerate code after modifying
                this file TODO: must have name of deployment too'
              type: object
            service:
              properties:
                cached:
                  properties:
                    ip:
                      type: string
                    loadBalancer:
                      description: LoadBalancer contains the current status of the
                        load-balancer, if one is present.
                      type: object
                    name:
                      type: string
                  type: object
                noCached:
                  properties:
                    ip:
                      type: string
                    loadBalancer:
                      description: LoadBalancer contains the current status of the
                        load-balancer, if one is present.
                      type: object
                    name:
                      type: string
                  type: object
              type: object
            vcl:
              properties:
                availability:
                  type: string
                configMapVersion:
                  type: string
                version:
                  type: string
              required:
              - configMapVersion
              - availability
              type: object
          required:
          - vcl
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
