apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: {{ printf "%scontroller-manager-service" .Values.namePrefix | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  ports:
  - port: 443
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
