apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: varnishservices.icm.ibm.com
spec:
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          properties:
            name:
              # limit name to 40 chars due to k8s length limits
              type: string
              maxLength: 40
        spec:
          properties:
            statefulSet:
              properties:
                updateStrategy:
                  properties:
                    type:
                      type: string
                      enum:
                        - OnDelete
                        - RollingUpdate
                        - DelayedRollingUpdate
            service:
              properties:
                varnishPort:
                  properties:
                    name:
                      type: string
                      maxLength: 15 #pod port name can't be more than 15 chars
                varnishExporterPort:
                  properties:
                    name:
                      type: string
                      maxLength: 15 #pod port name can't be more than 15 chars
