- op: add
  path: "/spec/versions/0/schema/openAPIV3Schema/properties/metadata"
  value:
    type: object
    properties:
      name: {}
- op: add
  path: "/spec/versions/0/schema/openAPIV3Schema/properties/metadata/properties/name"
  value:
    type: string
    maxLength: 40
