apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8329"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
    operator: varnish-operator
  name: varnish-operator-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: prometheus-metrics
      port: 8329
      targetPort: metrics
    - name: webhook
      port: 443
      targetPort: webhook
  selector:
    operator: varnish-operator