apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: '1.0'
  name: varnishservices.icm.ibm.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.deployment.replicas
    description: desired number of varnish pods
    name: Desired
    priority: 0
    type: integer
  - JSONPath: .status.deployment.readyReplicas
    description: current number of varnish pods
    name: Current
    priority: 0
    type: integer
  - JSONPath: .status.deployment.updatedReplicas
    description: number of varnish pods that are up to date
    name: Up-To-Date
    priority: 0
    type: integer
  - JSONPath: .status.service.cached.ip
    description: IP Address of the cached service
    name: Cached-Service-IP
    priority: 0
    type: string
  - JSONPath: .status.service.nocached.ip
    description: IP Address of the nocached service
    name: Nocached-Service-IP
    priority: 0
    type: string
  - JSONPath: .status.vcl.configMapVersion
    description: version of the ConfigMap containing the VCL
    name: VCL-Version
    priority: 0
    type: string
  group: icm.ibm.com
  names:
    kind: VarnishService
    plural: varnishservices
    shortNames:
    - vs
  scope: Namespaced
  subresources:
    scale:
      specReplicasPath: .spec.deployment.replicas
      statusReplicasPath: .status.deployment.replicas
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          properties:
            name:
              maxLength: 40
              type: string
          type: object
        spec:
          properties:
            deployment:
              properties:
                affinity:
                  type: object
                container:
                  properties:
                    image:
                      type: string
                    imagePullPolicy:
                      type: string
                    imagePullSecret:
                      type: string
                    livenessProbe:
                      properties:
                        exec:
                          properties:
                            command:
                              items:
                                type: string
                              type: array
                      type: object
                    readinessProbe:
                      properties:
                        exec:
                          properties:
                            command:
                              items:
                                type: string
                              type: array
                      type: object
                    resources:
                      type: object
                    restartPolicy:
                      type: string
                    varnishArgs:
                      items:
                        type: string
                      type: array
                  required:
                  - image
                  - imagePullSecret
                  type: object
                replicas:
                  format: int32
                  type: integer
                tolerations:
                  items:
                    type: object
                  type: array
              type: object
            logFormat:
              enum:
              - json
              - console
              type: string
            logLevel:
              enum:
              - debug
              - info
              - warn
              - error
              - dpanic
              - panic
              - fatal
              type: string
            podDisruptionBudget:
              type: object
            service:
              properties:
                prometheusAnnotations:
                  type: boolean
                varnishExporterPort:
                  properties:
                    name:
                      maxLength: 15
                      type: string
                  type: object
                varnishPort:
                  properties:
                    name:
                      maxLength: 15
                      type: string
                  type: object
              type: object
            vclConfigMap:
              properties:
                entrypointFile:
                  type: string
                name:
                  type: string
              required:
              - name
              - entrypointFile
              type: object
          required:
          - vclConfigMap
          - deployment
          - service
          type: object
        status:
          properties:
            deployment:
              type: object
            service:
              properties:
                cached:
                  properties:
                    ip:
                      type: string
                    loadBalancer:
                      type: object
                    name:
                      type: string
                  type: object
                noCached:
                  properties:
                    ip:
                      type: string
                    loadBalancer:
                      type: object
                    name:
                      type: string
                  type: object
              type: object
            vcl:
              properties:
                availability:
                  type: string
                configMapVersion:
                  type: string
                version:
                  type: string
              required:
              - configMapVersion
              - availability
              type: object
          required:
          - vcl
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: []
  storedVersions: []
