apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: varnish-operator
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - name: prometheus-metrics
    port: 9131
    targetPort: {{ .Values.container.metricsPort }}
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
