apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: varnish-operator
rules:
- apiGroups:
  - icm.ibm.com
  resources:
  - varnishservices
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - icm.ibm.com
  resources:
  - varnishservices/status
  verbs:
  - update
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ''
  resources:
  - services
  - serviceaccounts
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ''
  resources:
  - endpoints
  verbs:
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - watch
  - list
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - create
  - list
  - update
  - watch
  - delete
