apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: varnish-operator
  namespace: {{ .Values.namespace | quote }}
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: varnish-service-controller-manager-service
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
        admission-controller: "varnish-service-admission-controller"
    spec:
      containers:
      - name: manager
        image: {{ .Values.container.image | quote }}
        imagePullPolicy: {{ .Values.container.imagePullPolicy | title | quote }}
        env:
        - name: NAMESPACE
          value: {{ .Values.namespace | quote }}
        - name: LEADERELECTION_ENABLED
          value: {{ .Values.leaderElection.enabled | quote }}
        - name: LEADERELECTION_ID
          value: {{ .Values.leaderElection.id | quote }}
        - name: CONTAINER_IMAGE
          value: {{ .Values.container.image | quote }}
        - name: LOGLEVEL
          value: {{ .Values.logLevel | quote }}
        - name: LOGFORMAT
          value: {{ .Values.logFormat | quote }}
        resources: {{ toYaml .Values.container.resources | nindent 10 -}}
      restartPolicy: {{ .Values.container.restartPolicy | quote }}
      imagePullSecrets:
      - name: {{ .Values.container.imagePullSecret | quote }}
      terminationGracePeriodSeconds: 10
