apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: varnishservices.icm.ibm.com
spec:
  group: icm.ibm.com
  names:
    kind: VarnishService
    plural: varnishservices
    shortNames:
    - vs
  scope: Namespaced
  subresources:
    scale:
      specReplicasPath: .spec.deployment.replicas
      statusReplicasPath: .status.deployment.replicas
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            deployment:
              properties:
                affinity:
                  type: object
                backendsFile:
                  type: string
                defaultFile:
                  type: string
                imagePullSecretName:
                  type: string
                livenessProbe:
                  type: object
                readinessProbe:
                  type: object
                replicas:
                  format: int32
                  type: integer
                sharedVolume:
                  properties:
                    name:
                      type: string
                    path:
                      type: string
                  required:
                  - name
                  - path
                  type: object
                tolerations:
                  items:
                    type: object
                  type: array
                varnishExporterResources:
                  type: object
                varnishMemory:
                  type: string
                varnishResources:
                  type: object
                varnishRestartPolicy:
                  type: string
              required:
              - replicas
              - imagePullSecretName
              type: object
            service:
              properties:
                ports:
                  maxItems: 1
                  type: array
              type: object
          required:
          - service
          - deployment
          type: object
        status:
          properties:
            deployment:
              type: object
            service:
              properties:
                cached:
                  properties:
                    ip:
                      type: string
                    loadBalancer:
                      type: object
                  type: object
                noCached:
                  properties:
                    ip:
                      type: string
                    loadBalancer:
                      type: object
                  type: object
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
