[prune]
  go-tests = true

[[constraint]]
name = "github.com/caarlos0/env"
version = "v3.2.0"

[[override]]
name="github.com/go-logr/logr"
revision="9fb12b3b21c5415d16ac18dc5cd42c1cfdd40c4e"

[[override]]
name="github.com/go-logr/zapr"
revision="7536572e8d55209135cd5e7ccf7fce43dca217ab"

[[override]]
name="github.com/juju/errors"
branch="master"

[[override]]
name="go.uber.org/zap"
version="v1.8.0"

[[override]]
name="k8s.io/api"
version="kubernetes-1.10.0"

[[override]]
name="k8s.io/apimachinery"
version="kubernetes-1.10.0"

[[override]]
name="k8s.io/client-go"
version="kubernetes-1.10.1"

[[override]]
name="k8s.io/kube-openapi"
revision="f08db293d3ef80052d6513ece19792642a289fea"
