apiVersion: caching.ibm.com/v1alpha1
kind: VarnishCluster
metadata:
  labels:
    app: varnish
  name: {{ .Release.Name }}-varnish
  namespace: {{ .Release.Namespace }}
spec:
  vcl:
    configMapName: {{ .Release.Name }}-vcl-files
    entrypointFileName: entrypoint.vcl
  backend:
    selector:
      {{ toYaml .Values.varnish.backendsSelector | nindent 6 }}
    port: {{ .Values.varnish.backendsPort }}
  service:
    port: 80
