# Number of pods running the operator
replicas: 1
container:
  # path to image + tag
  image: us.icr.io/icm-varnish/varnish-operator:0.24.1
  # Image pull secret used to pull the operator image

  # imagePullSecret: docker-reg-secret
  # imagePullPolicy for Varnish Operator image
  imagePullPolicy: Always
  # restart policy for Varnish Operator containers
  restartPolicy: Always
  # resource limits and requests for Varnish Operator containers
  resources:
    limits:
      cpu: 500m
      memory: 200Mi
    requests:
      cpu: 500m
      memory: 200Mi
# logging level: "debug", "info", "warn", "error"
logLevel: info
# logging encoder: "json", "console"
logFormat: json
monitoring:
  grafanaDashboard:
    enabled: false
    namespace: ""
    labels:
      grafana_dashboard: "1"
    datasourceName: ""
  prometheusServiceMonitor:
    enabled: false
    namespace: ""
    labels:
      operator: varnish-operator
    scrapeInterval: 30s
