name: Build & Push Containers

on:
  release:
    types:
      - created

jobs:
  operator:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -f Dockerfile .
  varnishd:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -f Dockerfile.varnishd .
  varnish-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -f Dockerfile.controller .
  varnish-metrics-exporter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -f Dockerfile.exporter .
