name: Containers

on:
  release:
    types:
      - created

jobs:
#  operator:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v2
#      - uses: docker/build-push-action@v1
#        with:
#          username: test
#          password: test
#          repository: us.icr.io/icm-varnish/varnish-operator
#          always_pull: false
#          tag_with_ref: "refs/tags/{git-tag}"
#          dockerfile: "{path}/Dockerfile"
#          push: false
  operator:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -t ibmcom/varnish-operator -f Dockerfile .
  varnishd:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -t ibmcom/varnish-operator-varnish -f Dockerfile.varnishd .
  varnish-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -t ibmcom/varnish-controller -f Dockerfile.controller .
  varnish-metrics-exporter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -t ibmcom/varnish-operator-varnish -f Dockerfile.varnishd .
