name: Containers

on:
  push:
    branches: [ open-source ]

jobs:
  operator:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v1
        with:
          username: test
          password: test
          repository: us.icr.io/icm-varnish/varnish-operator
          always_pull: false
          tag_with_ref: "refs/tags/{git-tag}"
          dockerfile: "{path}/Dockerfile"
          push: false