name: end-to-end tests

on:
  push:
    branches: [ open-source ]
jobs:

  tests:
    name: End to end tests
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Cache Go dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Get dependencies
        run: go mod download
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.0.0-rc.1
        with:
          - config: e2e-tests-kubeconfig
      - name: build images
        run: |
          docker build -f Dockerfile  -t us.icr.io/icm-varnish/varnish-operator:local .
          docker build -f Dockerfile.varnishd  -t us.icr.io/icm-varnish/varnish:local .
          docker build -f Dockerfile.controller  -t us.icr.io/icm-varnish/varnish-controller:local .
          docker build -f Dockerfile.exporter  -t us.icr.io/icm-varnish/varnish-metrics-exporter:local .
#      - name: run tests
#        run: e2e-tests-kubeconfig
#        env:
#          KUBECONFIG: e2e-tests-kubeconfig
