name: Go

on:
  push:
    branches: [ open-source ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
    - name: Setup Kubebuilder assets
      run: |
        wget -O kubebuilder.tgz https://go.kubebuilder.io/dl/2.3.1/linux/amd64;
        tar -C /tmp/ -xzf kubebuilder.tgz;
        rm kubebuilder.tgz;
        echo "::set-env name=KUBEBUILDER_ASSETS::/tmp/kubebuilder_2.3.1_linux_amd64/bin"
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Cache Go dependencies
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: go mod download

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.26

    - name: Unit tests
      run: |
        wget -O kubebuilder.tgz https://go.kubebuilder.io/dl/2.3.1/linux/amd64;
        tar -C /tmp/ -xzf kubebuilder.tgz;
        rm kubebuilder.tgz;
        export KUBEBUILDER_ASSETS=/tmp/kubebuilder_2.3.1_linux_amd64/bin
        go test github.com/ibm/varnish-operator/pkg/... github.com/ibm/varnish-operator/cmd/... github.com/ibm/varnish-operator/api/... -coverprofile cover.out

  docs:
    name: Docs
    runs-on: ubuntu-latest
    container:
      image: node:10.16-jessie
    steps:
      - name: install gitbook
        run: npm install -g gitbook-cli@2.3.2
      - name: build docs
        run: |
          gitbook install ./docs
          gitbook build ./docs docs_generated --log=debug --debug
          cd docs_generated/
          git init
          git add .
          git config --local user.name \"Tomash Sidei\"
          git config --local user.email \"tomash.sidei@ibm.com\"
          git commit -m "Deploy Docs from Actions"
          git push --force --quiet https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:gh-pages
