name: Helm chart

on:
  push:
    branches: [ open-source ]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: src
      - name: Check out gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Check out helm releases
        uses: actions/checkout@v2
        with:
          path: helm-releases
      - name: Prepare helm-releases repo
        run: |
          cd helm-releases
          mkdir -p helm-releases
          find . -mindepth 1 -name helm-releases -prune -o -exec rm -rf {} \;
      - name: Get tag
        run: echo ::set-output name=GIT_TAG::${GITHUB_REF/refs\/tags\//}
      - name: Get Helm
        run: |
          curl -Lo ./helm.tar.gz https://get.helm.sh/helm-v2.16.9-linux-amd64.tar.gz
          tar -zxvf ./helm.tar.gz && mv linux-amd64/helm bin/
      - name: package chart & push
        run: |
          ./bin/linux-amd64/helm package src/varnish-operator --app-version ${GIT_TAG} --version ${GIT_TAG} --destination helm-releases
          helm repo index helm-releases --url https://theweathercompany.github.io/helm-releases
          cd helm-releases
          git commit -a -m "releases ${GIT_TAG}"
          git push origin helm-releases:helm-releases
          cd ../docs
          cp -f ../helm-releases .
          git commit -a -m "add helm chart for release ${GIT_TAG}
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages:gh-pages
